### PR TITLE
Boolean comparison fix

### PR DESCRIPTION
**Pull request by Phieleia**
Just changed == to === in some other places that I found.

### CODE REVIEW

**Comment by Phieleia** [comment]
The only occurence of `$this->data['busy'];` that I found **in that particular class** was a boolean value. But, unfortunately, I'm not sure...

**Comment by Fhizbang** [comment]
`$this->data` is an array with mixed datatypes. `data` is used across various classes in the code. but `data['busy']` is always a boolean (indicates if a building is currently busy or not).

**Comment by BlackScorp** [comment]
@Fhizbang the problem is that if in the database the value "1" is stored, then PHP convert automatically the 1 to true, but if we change the if statement to === then php will not convert the 1 to true it will let the 1 stay as integer and since 0 and false are different things (one is an integer. other is a boolean) the if statement will fail everytime.

unless you cast the manually the value.

`    if((bool)$this->data['busy'] === false) `

then it will work like it worked before

**Comment by Fhizbang** [comment]
don't know if that helps: this value is not saved in the DB. in fact only a very few values are saved. most of them are calculated when a new object instance is created.

i would keep it like before, but this discussion is (again) good for me to learn how things work

**Comment by BlackScorp** [comment]
actually there should not a discussion, just wanted to say that @Phieleia forgot to cast the values to bool before compare them.

**Comment by Fhizbang** [comment]
Ok, has been incorporated.

**Pull request merged**
